### ISSUE TITLE
Errors during building Examples

### ISSUE THREAD

**Issue by kartoch** [sebastien/tahchee#6]
When building `Documentation/Example/` (using Ubuntu 10.10) I've several warning and error messages:

```
/usr/bin/env python build.py local
tahchee v.1.0.1
/home/kartoch/opt/python/tahchee/Sources/tahchee/main.py:236: DeprecationWarning: os.popen3 is deprecated.  Use the subprocess module.
  _in, _out, _err = os.popen3("%s -v" % tidypath)
 [ ] Found tidy in default path
 [#] Tidy enables HTML file clean-up and compression but is disabled
 [#] See the TIDY and TIDY_USE options or check tidy is your path
 [ ] Mode is 'local', generating in 'Site/Local'
 [ ] Changes are detected by date
 [ ] Generating templates Python module:/home/kartoch/Documents/Netkit/www/Templates/__init__.py
 [ ] Precompiling template 'Templates/Base'
 [ ] Precompiling template 'Templates/Page'
 [ ] Copying  '/home/kartoch/Documents/Netkit/www/Site/Local/screen.css'
 [ ] Generating file 'restpage.html'
<string>:: (ERROR/3) Anonymous hyperlink mismatch: 12 references but 3 targets.
See "backrefs" attribute for IDs.
 [ ] Generating file 'index.html'
 [ ] Copying  '/home/kartoch/Documents/Netkit/www/Site/Local/dependency-1.data'
```

The first error seems related to old python version (I'm using Python 2.6.6).

The second error is strange: If i'm changing `USE_TIDY` to `True` in `build.py`, I've the following stacktrace:

```
Traceback (most recent call last):
  File "build.py", line 25, in <module>
    site = Site(URL, locals=locals())
  File "/home/kartoch/opt/python/tahchee/Sources/tahchee/main.py", line 218, in __init__
    self._processOptions(locals)
  File "/home/kartoch/opt/python/tahchee/Sources/tahchee/main.py", line 269, in _processOptions
    if has("USE_TIDY").lower() == "no" or not has("USE_TIDY") or not self._tidy:
AttributeError: 'bool' object has no attribute 'lower'
make: *** [local] Error 1
```

The last one seems to be related to backlinks. Any hints ?

**Comment by kartoch** [comment]
Roten issue, closing it
